# Configure Rolls
rollFormula = "2d6"

# Configure stat toggle label and formula modifier.
[statToggle]
  label = "Highlight"
  modifier = "-1"

# Define roll result ranges.
[rollResults]
  [rollResults.failure]
    range = "6-"
    label = "Complications..."
  [rollResults.partial]
    range = "7-9"
    label = "Partial success"
  [rollResults.success]
    range = "10-12"
    label = "Success!"
  [rollResults.critical]
    range = false
    label = "Critical Success!"

########################################
## CHARACTERS ##########################
########################################
# Define the character group.
[character]

  # Define stats.
  [character.stats]
    cool = "Cool"
    hard = "Hard"
    hot = "Hot"
    sharp = "Sharp"
    weird = "Weird"

  # Define attributes.
  [character.attributesTop]
    [character.attributesTop.armor]
      label = "Armor"
      type = "Number"
    [character.attributesTop.harm]
    	label = "Harm"
      type = "Clock"
      max = 6
      default = 0
    [character.attributesTop.improvement]
      label = "Improvement"
      type = "Xp"
      max = 7
    [character.attributesTop.customResource]
      label = "Custom Resource That Wraps Lines"
      type = "Resource"
      max = 4
      default = 2

  # Define sidebar details.
  [character.attributesLeft]
    # Example of short-syntax fields.
    look = "LongText"
    hx = "LongText"
    number = "Number"
    #  Define a conditions field with several options.
		[character.attributesLeft.conditions]
      label = "Conditions"
    	type = "ListMany"
      description = "Choose all that apply:"
      # Define options for the conditions field.
      [character.attributesLeft.conditions.options]
      	afraid = "Afraid"
        angry = "Angry"
        guilty = "Guilty"
        hopeless = "Hopeless"
        insecure = "Insecure"

  # Define groups for moves.
  [character.moveTypes]
    basic = "Basic"
    advanced = "Advanced"

  # Define groups for equipment.
  [character.equipmentTypes]
    gear = "Gear"
    loot = "Loot"

########################################
## NPCS ################################
########################################
# Define stats.
[npc]
  # NPCs don't support stats at this time.
  stats = false

  # Define attributes.
  [npc.attributesTop]
    [npc.attributesTop.armor]
      label = "Armor"
      type = "Number"
    [npc.attributesTop.harm]
      label = "Harm"
      type = "Clock"
      max = 6
    [npc.attributesTop.damage]
      label = "Damage"
      type = "Roll"
      default = "d10"

  [npc.attributesLeft]
    [npc.attributesLeft.bio]
      label = "Bio"
      type = "LongText"
    [npc.attributesLeft.choices]
    	type = "ListMany"
      label = "Several Choices That Wrap"
      description = "Choose all that apply:"
      [npc.attributesLeft.choices.options]
      	afraid = "Afraid"
        angry = "Angry"
        guilty = "Guilty"
        hopeless = "Hopeless"
        insecure = "Insecure"
    [npc.attributesLeft.choice]
    	type = "ListMany"
      label = "Single Choice"
      description = "Choose one:"
			options = [
				"one",
        "two",
        "three"
      ]

  # Define logical groups for moves.
  [npc.moveTypes]
    actions = "Actions"